### ISSUE TITLE
Not published on Packagist

### ISSUE THREAD

**Issue by helhum** [codeFareith/cf_beskin#2]
Can you please publish your extension on [Packagist](https://packagist.org/)?
Thanks.

**Comment by codeFareith** [comment]
Done

**Comment by helhum** [comment]
Thanks!

**Comment by helhum** [comment]
You could now add the package key to [TER](https://extensions.typo3.org/extension/cf_beskin/), so that the composer command to require the ext is shown on the detail page as well. Just edit the extension details after logging in.
